### ISSUE TITLE
Please！I need these function！

### ISSUE THREAD

**Issue by fanglangxinghai** [KUR-creative/SickZil-Machine#61]
1. I want to make piciture zoom in and out.
2. I want to undo the previous step (Ctrl + Z)  when i am doing mask work.

**Comment by KUR-creative** [comment]
Closed. Because it's duplicated issue.
#33 zoom-in/out 
#39 undo/redo

Before posting an issue, please check past open issues first.

And it's a good idea to reveal what you want in the issue title. 
In this case, it would be a **Request for undo/redo and zoom in and out functions**.

I know that these two features are the most needed. 
I'll do it as soon as possible.

Please wait for the next major version!

----

중복되는 이슈이므로 닫습니다.
#33 zoom-in/out 
#39 undo/redo

이슈를 올리기 전에 과거의 이슈를 먼저 살펴주세요.

그리고 이슈 제목으로 원하는 바를 드러내시는게 좋습니다.
이 경우에는 **작업 취소/재실행, 줌 인/아웃 기능 요청** 정도의 제목이면 좋겠습니다.

언급하신 두 기능이 가장 필요한 기능인 것은 저도 알고 있습니다. 
가능하면 빨리 처리해보겠습니다.

다음 버전을 기다려 주세요!
